version: "2"
services:
  cordova-ui:
    image: openlmis/dev-ui:5
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - cce-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
    depends_on:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - cce-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
  auth-ui:
    image: openlmis/auth-ui:5.0.4-SNAPSHOT
    volumes:
      - '/openlmis-auth-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.2.2-SNAPSHOT
    volumes:
      - '/openlmis-referencedata-ui'
  ui-components:
    image: openlmis/ui-components:5.1.2-SNAPSHOT
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.0.3-SNAPSHOT
    volumes:
      - '/openlmis-ui-layout'
  image:
    build: .
    image: openlmis/reference-ui
